version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: "cimg/node:18.12.1"
    steps:
      - checkout
      - node/install
      - run: "npm i && npm run test"
    
workflows:
  build:
    jobs:
      - test


# VS Code Extension Version: 1.0.2