version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
      - run: "npm i"
    
workflows:
  build:
    jobs:
      - test

