version: 2.1

jobs:
  test:
    parameters:
      node_version:
        type: string
    docker:
      - image: 'cimg/node:<< parameters.node_version >>'
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          name: Restore npm cache
          keys:
            - v1-node-modules-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          name: Save npm cache
          key: v1-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: |
            mkdir -p ~/reports
            npm run test-report > ~/reports/ava.xml
      - store_test_results:
          path: ~/reports

workflows:
  build:
    jobs:
      - test:
          matrix:
            parameters:
              node_version:
                - '21.7.3'
                - '22.15.0'
                - '23.11.0'
